language: "hu_core_news_lg"

pipeline:
  - name: services.delete_special_chars.DeleteSpecialChars
  - name: SpacyNLP
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: DIETClassifier
    epochs: 50
    entity_recognition: False
  - name: FallbackClassifier
    threshold: 0.25
  - name: ResponseSelector
    epochs: 50

policies:
   - name: RulePolicy
